### ISSUE TITLE
Dashboard card  column under Bookmark statistics is different to rest of columns "0.99.100"

### ISSUE THREAD

**Issue by PQYPLZXHGF** [cdhorn/CardView#199] opened 2022-06-16 08:57 UTC
Dashboard card  column under Bookmark statistics is different to rest of columns
![](https://user-images.githubusercontent.com/212355/174033494-5ead3fa0-0e87-4a12-a59d-07169cbbf660.png)

**Comment by cdhorn** [comment] 2022-06-26 14:42
This might be fixed now, at least I did not see it when I quick checked under my Windows VM. If someone who could consistently reproduce this can confirm would appreciate it.

**Comment by cdhorn** [comment] 2022-06-30 02:16
This seems to be fixed now, so closing this.

**Closed by cdhorn** 2022-06-30 02:16 UTC
